"""Models module exports."""

from models.models import (
    Intersection,
    TrafficCamera,
    VehicleCount,
    SignalStateRecord,
    TrafficMetric,
    EmergencyEvent,
    CongestionLevel,
    SignalState,
    VehicleType,
    EmergencyType
)

from models.schemas import (
    IntersectionBase,
    IntersectionCreate,
    IntersectionUpdate,
    IntersectionResponse,
    CameraBase,
    CameraCreate,
    CameraUpdate,
    CameraResponse,
    VehicleCountBase,
    VehicleCountCreate,
    VehicleCountResponse,
    SignalStateBase,
    SignalStateCreate,
    SignalStateUpdate,
    SignalStateResponse,
    TrafficMetricBase,
    TrafficMetricCreate,
    TrafficMetricResponse,
    EmergencyEventBase,
    EmergencyEventCreate,
    EmergencyEventUpdate,
    EmergencyEventResponse,
    RealtimeTrafficUpdate,
    RealtimeEmergencyAlert,
    TrafficAnalytics,
    IntersectionAnalytics,
    DashboardSummary,
    DetectionResult
)

__all__ = [
    # Models
    "Intersection",
    "TrafficCamera",
    "VehicleCount",
    "SignalStateRecord",
    "TrafficMetric",
    "EmergencyEvent",
    # Enums
    "CongestionLevel",
    "SignalState",
    "VehicleType",
    "EmergencyType",
    # Schemas
    "IntersectionBase",
    "IntersectionCreate",
    "IntersectionUpdate",
    "IntersectionResponse",
    "CameraBase",
    "CameraCreate",
    "CameraUpdate",
    "CameraResponse",
    "VehicleCountBase",
    "VehicleCountCreate",
    "VehicleCountResponse",
    "SignalStateBase",
    "SignalStateCreate",
    "SignalStateUpdate",
    "SignalStateResponse",
    "TrafficMetricBase",
    "TrafficMetricCreate",
    "TrafficMetricResponse",
    "EmergencyEventBase",
    "EmergencyEventCreate",
    "EmergencyEventUpdate",
    "EmergencyEventResponse",
    "RealtimeTrafficUpdate",
    "RealtimeEmergencyAlert",
    "TrafficAnalytics",
    "IntersectionAnalytics",
    "DashboardSummary",
    "DetectionResult"
]
